# Generated by Django 4.1.5 on 2023-02-08 16:20

import collector.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone_number',
            field=models.CharField(max_length=20, unique=True, validators=[collector.models.validate_phone_number]),
        ),
    ]
